version: "3"

# networks:
#   backend:
#     driver: bridge

services:
  mng-nginx:
    build:
      context: .
      dockerfile: ./docker/mng-nginx/Dockerfile
    volumes:
      - "./src/mng/www:/var/www/management/www"
      - "./src/mng/libs_ver2.0:/var/www/management/libs_ver2.0"
    ports:
      - "8000:80"
    depends_on:
      - mng-php-fpm
  mng-php-fpm:
    build:
      context: .
      dockerfile: ./docker/mng-php-fpm/Dockerfile
    volumes:
      - "./src/mng/www:/var/www/management/www"
      - "./src/mng/libs_ver2.0:/var/www/management/libs_ver2.0"
    depends_on:
      - master_db
      - queue_db
      - queue
    links:
      - master_db
      - queue
      - queue_db
  api-nginx:
    build:
      context: .
      dockerfile: ./docker/api-nginx/Dockerfile
    volumes:
      - "./src/api/www:/var/www/api/www"
      - "./src/api/libs_ver2.0:/var/www/api/libs_ver2.0"
    ports:
      - "8080:80"
    depends_on:
      - mng-php-fpm
  api-php-fpm:
    build:
      context: .
      dockerfile: ./docker/api-php-fpm/Dockerfile
    volumes:
      - "./src/api/www:/var/www/api/www"
      - "./src/api/libs_ver2.0:/var/www/api/libs_ver2.0"
    depends_on:
      - master_db
      - queue_db
      - queue
    links:
      - master_db
      - queue_db
      - queue
  cron:
    build:
      context: .
      dockerfile: ./docker/cron/Dockerfile
    volumes:
      - "./src/mng/libs_ver2.0:/var/www/management/libs_ver2.0"
    depends_on:
      - master_db
      - queue_db
      - queue
    links:
      - master_db
      - queue
      - queue_db
  queue:
    build:
      context: .
      dockerfile: ./docker/queue/Dockerfile
  queue_worker:
    build:
      context: .
      dockerfile: ./docker/queue_worker/Dockerfile
    volumes:
      - "./src/queue_worker/scripts:/var/www/queue_worker/scripts"
      - "./src/queue_worker/libs_ver2.0:/var/www/queue_worker/libs_ver2.0"
    depends_on:
      - master_db
      - queue_db
      - queue
    links:
      - master_db
      - queue_db
      - queue
  master_db:
    build:
      context: .
      dockerfile: ./docker/master_db/Dockerfile
    command: mysqld --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    volumes:
      - ./data/master_db:/var/lib/mysql
    # ports:
    #   - 3307:3306
    # networks:
    #   - backend
  queue_db:
    build:
      context: .
      dockerfile: ./docker/queue_db/Dockerfile
    command: mysqld --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    volumes:
      - ./data/queue_db:/var/lib/mysql
    # ports:
    #   - 3308:3306
    # networks:
    #   - backend
  core_db_client:
    container_name: core_db_client
    ports:
      - 8081:8080
    image: phpmyadmin:5.1.3-fpm-alpine
    links:
      - queue_db
      - master_db
    # networks:
    #   - backend
