FROM mysql:8.0.29
ENV MYSQL_DATABASE=coreasp_v2_master
ENV MYSQL_USER=coreaspdbmaster
ENV MYSQL_PASSWORD='Ns918\$jaH82NmRr!eGw7'
ENV MYSQL_ROOT_PASSWORD=root
COPY ./docker/master_db/*.sql /docker-entrypoint-initdb.d